## Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [2]:
import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[ 0.67629388  0.24565041 -0.58408238 -0.81056039 -1.8773199  -0.34776414
 -1.55750892  0.4600891   0.74450302  0.08629123  0.75886342  0.44917366
 -0.065672    0.62622     0.64953255  1.07786492  1.25973524 -0.6436162
  1.31889368 -0.60357365  0.6394236  -0.22888922 -0.5928749   0.75523251
 -0.26511897]


## Create a random vector of size 30 and find the mean value.

In [3]:
Z = np.random.random(10)
m = Z.mean()
print (m)

0.6046707132237882


## Insert 1 to 100 numbers in a NumPy array and reshape it to 10*10 matrix.

In [4]:
import numpy as np
a = np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.87285607 0.63556022 0.80288797 0.90841118 0.94177614 0.22569043
  0.99254818 0.57649975 0.52110738 0.56411459]
 [0.60652535 0.1937799  0.56186246 0.13304764 0.38208708 0.76264588
  0.08466336 0.41779422 0.59784256 0.18805187]
 [0.88472685 0.96905979 0.5344797  0.18013172 0.43006916 0.27972513
  0.99173822 0.99149405 0.50589559 0.26372464]
 [0.01382772 0.09613225 0.33897465 0.09524045 0.31736188 0.99188451
  0.85236772 0.33122205 0.66050356 0.25149853]
 [0.02501313 0.7167919  0.74897432 0.61297352 0.55185917 0.99114899
  0.00470542 0.09964997 0.55662814 0.64343869]
 [0.2784309  0.04898508 0.64998515 0.26316384 0.04195059 0.358206
  0.30142059 0.75437473 0.00301593 0.25580397]
 [0.88262059 0.64406771 0.95224832 0.76187688 0.82397046 0.60343791
  0.79267341 0.39533407 0.03537289 0.01637857]
 [0.39298652 0.2998484  0.46246069 0.01898151 0.79886999 0.38270945
  0.27288213 0.33888797 0.95898449 0.08537421]
 [0.05199985 0.06180917 0.07926437 0.64222915 0.93867086 0.5632443

## Find Dot product of two arrays f = np.array([1,2]) g = np.array([4,5])

In [9]:
f = np.array([1,2])

g = np.array([4,5])
print(np.dot(f,g, out=None))

14


## Concatenate following arrays along axis=0 x=np.array([[1,2],[3,4]]) y=np.array([[5,6]])

In [12]:
x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])
print(np.concatenate((x,y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


## How to get the common items between two python NumPy arrays? a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


## Sort the numpy array: arr = np.array([10,5,8,4,7,2,3,1])

In [15]:
arr = np.array([10,5,8,4,7,2,3,1])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  7,  8, 10])